In [64]:
import pandas as pd
import numpy as np
df= pd .read_csv('Desktop/project/flats.csv')
df

size  bdrooms  price
0   1000        2   2000
1   1500        2   3000
2   2000        3   6000
3   3000        1   3000
4   3220        4  12880
5   3600        8  28800
6   4500        1   4500
7   5100        7  35700
8   6000        3  18000
9   6300        1   6300
10  7000        4  28000
11  7800        5  39000

In [6]:
d=np.array(df['size'])
d.shape

(12,)

In [65]:
g=[]
for i in range(len(df['size'])):
    x=1
    g.append(x)
df['x']=g
df

size  bdrooms  price  x
0   1000        2   2000  1
1   1500        2   3000  1
2   2000        3   6000  1
3   3000        1   3000  1
4   3220        4  12880  1
5   3600        8  28800  1
6   4500        1   4500  1
7   5100        7  35700  1
8   6000        3  18000  1
9   6300        1   6300  1
10  7000        4  28000  1
11  7800        5  39000  1

In [67]:
k=np.array([df['x'],df['size'],df['bdrooms']])
k=k.T
k


array([[   1, 1000,    2],
       [   1, 1500,    2],
       [   1, 2000,    3],
       [   1, 3000,    1],
       [   1, 3220,    4],
       [   1, 3600,    8],
       [   1, 4500,    1],
       [   1, 5100,    7],
       [   1, 6000,    3],
       [   1, 6300,    1],
       [   1, 7000,    4],
       [   1, 7800,    5]], dtype=int64)

In [70]:
y=np.array(df['price'])
y=y.T
y.shape

(12,)

In [81]:
u=(k.T).dot(k)
print(u)
print(u.shape)

[[       12     51020        41]
 [    51020 271368400    187180]
 [       41    187180       199]]
(3, 3)


In [72]:
r=(k.T).dot(y)
r
print(r.shape)

(3,)


In [98]:
from numpy.linalg import inv

h=inv(u)
print(h)


[[ 5.19474058e-01 -6.78883881e-05 -4.31712959e-02]
 [-6.78883881e-05  1.93645971e-08 -4.22734359e-06]
 [-4.31712959e-02 -4.22734359e-06  1.78959664e-02]]


In [99]:
h.dot(u)

array([[ 1.00000000e+00, -3.63797881e-12, -7.10542736e-15],
       [ 1.35525272e-19,  1.00000000e+00,  3.25260652e-19],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [74]:
m=l.dot(r)
m

array([-1.25541635e+04,  3.14903316e+00,  4.32112903e+03])

In [76]:
a=m[0]
print(a)
b=m[1]
print(b)
c=m[2]
print(c)

-12554.163495748136
3.149033160451033
4321.129026896732


In [79]:
df

size  bdrooms  price  x
0   1000        2   2000  1
1   1500        2   3000  1
2   2000        3   6000  1
3   3000        1   3000  1
4   3220        4  12880  1
5   3600        8  28800  1
6   4500        1   4500  1
7   5100        7  35700  1
8   6000        3  18000  1
9   6300        1   6300  1
10  7000        4  28000  1
11  7800        5  39000  1

In [80]:
q=1000
j=2
t=a+b*q+c*j
t

-762.8722815036399