In [46]:
import pandas as pd
from numpy import*
df= pd .read_csv('Desktop/project/flats.csv')
df

size  bdrooms  price
0   1000        2   2000
1   1000        3   3000
2   1000        4   4000
3   2500        2   5000
4   2500        3   7500
5   2500        4  10000
6   4000        2   8000
7   4000        3  12000
8   4000        4  16000
9   4000        5  20000
10  6000        2  12000
11  6500        3  19500

In [47]:
g=[]
for i in range(len(df['size'])):
    x=1
    g.append(x)
df['x']=g
df

size  bdrooms  price  x
0   1000        2   2000  1
1   1000        3   3000  1
2   1000        4   4000  1
3   2500        2   5000  1
4   2500        3   7500  1
5   2500        4  10000  1
6   4000        2   8000  1
7   4000        3  12000  1
8   4000        4  16000  1
9   4000        5  20000  1
10  6000        2  12000  1
11  6500        3  19500  1

In [48]:
x=np.array([df['x'],df['size'],df['bdrooms']])
x=x.T
x
#matrix of 

array([[   1, 1000,    2],
       [   1, 1000,    3],
       [   1, 1000,    4],
       [   1, 2500,    2],
       [   1, 2500,    3],
       [   1, 2500,    4],
       [   1, 4000,    2],
       [   1, 4000,    3],
       [   1, 4000,    4],
       [   1, 4000,    5],
       [   1, 6000,    2],
       [   1, 6500,    3]], dtype=int64)

In [5]:
#farmula=inv(xT.x).xT.y


In [49]:
xT=x.T
xT

array([[   1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1],
       [1000, 1000, 1000, 2500, 2500, 2500, 4000, 4000, 4000, 4000, 6000,
        6500],
       [   2,    3,    4,    2,    3,    4,    2,    3,    4,    5,    2,
           3]], dtype=int64)

In [50]:
#now
xT.dot(x)

array([[       12,     39000,        37],
       [    39000, 164000000,    119000],
       [       37,    119000,       125]], dtype=int64)

In [51]:
y=np.array(df['price'])
print(xT.shape)
print(y.shape)#shapes are okay ...so we can multiply

(3, 12)
(12,)


In [52]:
xT.dot(y)
print(xT.dot(y))
print(xT.dot(y).shape)

[   119000 488000000    400000]
(3,)


In [53]:
#now we have to find inverse matri of (xT.x)
from numpy.linalg import inv
xTinv=inv(xT.dot(x))
xTinv

array([[ 1.30405266e+00, -9.70993623e-05, -2.93560996e-01],
       [-9.70993623e-05,  2.69491874e-08,  3.08578482e-06],
       [-2.93560996e-01,  3.08578482e-06,  9.19563876e-02]])

In [54]:
sd=xTinv.dot(xT.dot(y))
sd

array([-9.62662004e+03,  2.83069327e+00,  3.35465954e+03])

In [55]:
s=2500
t=2
kl=sd[0]+sd[1]*s+sd[2]*t
kl

4159.432215593519

In [45]:
np.allclose(xTinv)

TypeError: _allclose_dispatcher() missing 1 required positional argument: 'b'