In [4]:
a=[10,40,70,80]
b=[1,7,8,4]
a/b


TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [5]:
#so convert int arrays
import numpy as np
c=np.array(a)
d=np.array(b)
print(c/d)
print(a+b)
print(c+d)
print(c+5)
print(c.dtype)
#and also here data memory is int32 ,but in pandas int64

[10.          5.71428571  8.75       20.        ]
[10, 40, 70, 80, 1, 7, 8, 4]
[11 47 78 84]
[15 45 75 85]
int32


In [10]:
f=np.array([1,2,6,'raki'])
f.dtype

dtype('<U11')

In [22]:
g=np.arange(9)
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
t=np.linspace(10,1,5)#linspace gives 10 to 2 ,5 equal difference numbers
t

array([10.  ,  7.75,  5.5 ,  3.25,  1.  ])

In [23]:
g.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:

g.reshape(1,2,5)# 3 dimensions :that is 1 row  2 elements in a row, and 5 columns

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [28]:
g.reshape(1,2,5,1)# four dimensions

array([[[[0],
         [1],
         [2],
         [3],
         [4]],

        [[5],
         [6],
         [7],
         [8],
         [9]]]])

In [31]:
t=np.arange(9)
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
d=t%2==0
print(d)

t[d]

[ True False  True False  True False  True False  True]


array([0, 2, 4, 6, 8])

In [64]:
print(np.eye(3))#identity matrix,no need bracket inside bracket
print(np.ones((3,3)))
print(np.zeros(2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0. 0.]


In [65]:
x=np.zeros((3,2))#backetinside  bracets are must to setsshape
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [73]:
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
x*5

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])